// Finance calculators content — Part 1 (core calculators)
'use strict';
module.exports = {
  emi: {
    why: 'Understanding your EMI before taking a loan is one of the most important financial decisions you can make. In India, the average home loan tenure spans 15–20 years, meaning a small difference in interest rate can translate to lakhs of rupees in savings. On a ₹50 lakh home loan, the difference between 8.5% and 9.0% over 20 years is approximately ₹3.2 lakhs in total interest. This calculator shows the complete cost breakdown including total interest paid, principal-to-interest ratio, and month-by-month amortization.',
    feats: ['Instant EMI for any loan amount, rate, and tenure','Complete amortization schedule with principal vs interest split','Visual pie chart of total cost breakdown','Supports home, car, personal, and education loans','Compare scenarios by adjusting rate or tenure','Works offline — your data never leaves your device'],
    tips: ['Negotiate your interest rate — even 0.25% lower saves lakhs over 20 years.','One extra EMI per year as prepayment can reduce a 20-year loan to ~16 years.','Keep total EMI-to-income ratio below 40% for financial flexibility.','Floating rate loans in India cannot charge prepayment fees per RBI rules.','Review your loan statement annually to track principal vs interest.'],
    who: 'Home buyers comparing loan offers, car buyers estimating monthly costs, financial planners advising on debt management, and anyone considering a personal loan.',
    formula: 'EMI = [P × R × (1+R)^N] / [(1+R)^N – 1], where P = Principal loan amount, R = Monthly interest rate (annual rate / 12 / 100), N = Total number of monthly instalments.',
    example: 'For a ₹50,00,000 home loan at 8.5% for 20 years: R = 8.5/12/100 = 0.00708, N = 240 months. EMI = [50,00,000 × 0.00708 × (1.00708)^240] / [(1.00708)^240 – 1] = ₹43,391 per month. Total payment = ₹1,04,13,840. Total interest = ₹54,13,840.',
    tbl: '<table><thead><tr><th>Loan Amount</th><th>Rate</th><th>Tenure</th><th>Monthly EMI</th><th>Total Interest</th></tr></thead><tbody><tr><td>₹25,00,000</td><td>8.5%</td><td>20 yrs</td><td>₹21,696</td><td>₹27,06,920</td></tr><tr><td>₹50,00,000</td><td>8.5%</td><td>20 yrs</td><td>₹43,391</td><td>₹54,13,840</td></tr><tr><td>₹75,00,000</td><td>9.0%</td><td>15 yrs</td><td>₹76,071</td><td>₹61,92,822</td></tr><tr><td>₹10,00,000</td><td>11.0%</td><td>5 yrs</td><td>₹21,742</td><td>₹3,04,520</td></tr></tbody></table>',
    tblCap: 'EMI comparison across common Indian loan scenarios (2026 rates)'
  },
  sip: {
    why: 'With over 8.5 crore SIP accounts active in India, monthly contributions have crossed ₹20,000 crore. The power of SIP lies in rupee-cost averaging — you buy more units when markets are low and fewer when high. A ₹10,000 monthly SIP returning 12% annually grows to approximately ₹1 crore in 20 years, with total investment of just ₹24 lakhs. Compounding generates ₹76 lakhs — more than 3x your actual investment.',
    feats: ['Calculate future value of any monthly SIP','Total invested vs wealth gained breakdown','Visual growth chart showing compounding','Step-up SIP support for annual increases','Reverse calculation — find SIP needed for target corpus','Compare different return rate scenarios'],
    tips: ['Start as early as possible — age 25 vs 35 means 3x more wealth at retirement.','Step-up SIP by 10% each year dramatically accelerates wealth creation.','Never stop SIP during market crashes — that is when you buy most units at lowest prices.','Choose direct plans over regular plans to save 0.5–1% in expense ratio.','Set up auto-debit for consistency — irregular investing is the biggest SIP mistake.'],
    who: 'Young professionals starting investing, parents saving for education, retirement planners, and anyone building wealth systematically.',
    formula: 'FV = P × [(1 + r)^n – 1] / r × (1 + r), where P = Monthly SIP amount, r = Monthly rate of return (annual/12/100), n = Total months.',
    example: 'For ₹10,000/month SIP at 12% for 20 years: r = 12/12/100 = 0.01, n = 240. FV = 10,000 × [(1.01)^240 – 1] / 0.01 × 1.01 = ₹99,91,479. Invested: ₹24,00,000. Wealth gained: ₹75,91,479.',
    tbl: '<table><thead><tr><th>Monthly SIP</th><th>Duration</th><th>Return</th><th>Invested</th><th>Estimated Value</th></tr></thead><tbody><tr><td>₹5,000</td><td>10 yrs</td><td>12%</td><td>₹6,00,000</td><td>₹11,61,695</td></tr><tr><td>₹10,000</td><td>15 yrs</td><td>12%</td><td>₹18,00,000</td><td>₹50,45,760</td></tr><tr><td>₹10,000</td><td>20 yrs</td><td>12%</td><td>₹24,00,000</td><td>₹99,91,479</td></tr><tr><td>₹25,000</td><td>25 yrs</td><td>12%</td><td>₹75,00,000</td><td>₹4,69,78,365</td></tr></tbody></table>',
    tblCap: 'SIP wealth creation at 12% average annual return'
  },
  gst: {
    why: 'GST, implemented on July 1, 2017, replaced 17 indirect taxes. With over 1.4 crore registered businesses and monthly collections exceeding ₹1.5 lakh crore, GST impacts virtually every transaction in India. The four-slab structure (5%, 12%, 18%, 28%) applies differently to goods and services, making accurate calculation essential for compliance.',
    feats: ['Calculate GST at any rate (5%, 12%, 18%, 28%, or custom)','Automatic CGST + SGST split for intra-state transactions','IGST mode for inter-state calculations','Reverse GST calculation from inclusive amount','Supports both goods and services','No login or signup required'],
    tips: ['Verify applicable GST rate — the schedule is updated quarterly by the GST Council.','Ensure GSTIN is valid before claiming Input Tax Credit.','For e-commerce sellers, TCS of 1% is deducted by the platform.','Keep purchase invoices for at least 6 years for ITC claims and audits.','Use HSN/SAC codes for correct rate classification.'],
    who: 'Small business owners, chartered accountants, consumers verifying charges, freelancers, and e-commerce sellers.',
    formula: 'GST Amount = Base Price × (GST Rate / 100). For inclusive: Base Price = Total / (1 + GST Rate/100). CGST = SGST = GST / 2 (intra-state). IGST = full GST (inter-state).',
    example: 'Product price ₹10,000, GST rate 18%: GST = 10,000 × 0.18 = ₹1,800. CGST = ₹900, SGST = ₹900. Total = ₹11,800. Reverse: If inclusive price is ₹11,800 at 18%, base = 11,800 / 1.18 = ₹10,000.',
    tbl: '<table><thead><tr><th>Slab</th><th>Common Items</th><th>On ₹10,000</th><th>Total</th></tr></thead><tbody><tr><td>5%</td><td>Packaged food, economy hotels</td><td>₹500</td><td>₹10,500</td></tr><tr><td>12%</td><td>Butter, mobile phones</td><td>₹1,200</td><td>₹11,200</td></tr><tr><td>18%</td><td>Most services, electronics</td><td>₹1,800</td><td>₹11,800</td></tr><tr><td>28%</td><td>Luxury cars, tobacco</td><td>₹2,800</td><td>₹12,800</td></tr></tbody></table>',
    tblCap: 'GST slabs with calculation examples'
  },
  taxregime: {
    why: 'With the new tax regime as default from FY 2023-24 and enhanced rebate of ₹12 lakh for FY 2025-26, choosing the right regime can save you lakhs. The old regime offers deductions under 80C (₹1.5L), 80D (₹75K), 24B (₹2L), and NPS 80CCD(1B) (₹50K). The new regime offers lower rates but no deductions.',
    feats: ['Compare Old vs New regime side-by-side','Updated for FY 2025-26 with latest slabs','Section 80C, 80D, 80CCD, 24B deduction support','4% Health and Education Cess included','Surcharge calculation for high incomes','Monthly and annual tax breakdowns'],
    tips: ['If total deductions exceed ₹3.75 lakh, old regime is likely better.','New regime rebate means zero tax up to ₹12 lakh income.','Maximize NPS for extra ₹50K deduction under 80CCD(1B).','File ITR before July 31 to avoid late fees.','Standard deduction of ₹75,000 available in new regime from FY 2024-25.'],
    who: 'Salaried professionals, CAs advising clients, HR departments, and retirees with pension income.',
    formula: 'Tax = Sum of (Income in each slab × slab rate). Old regime: ₹0-2.5L = 0%, ₹2.5-5L = 5%, ₹5-10L = 20%, above ₹10L = 30%. New regime: ₹0-3L = 0%, ₹3-7L = 5%, ₹7-10L = 10%, ₹10-12L = 15%, ₹12-15L = 20%, above ₹15L = 30%.',
    example: 'Income ₹15,00,000. New regime: 0 + (4L×5%) + (3L×10%) + (2L×15%) + (3L×20%) = ₹20,000 + ₹30,000 + ₹30,000 + ₹60,000 = ₹1,40,000 + 4% cess = ₹1,45,600. Old regime (with ₹3L deductions): Taxable = ₹12L. Tax = ₹1,12,500 + cess = ₹1,17,000.',
    tbl: '<table><thead><tr><th>Slab</th><th>Old Regime</th><th>New Regime FY 25-26</th></tr></thead><tbody><tr><td>Up to ₹3L</td><td>Nil</td><td>Nil</td></tr><tr><td>₹3L–7L</td><td>5% (above ₹2.5L)</td><td>5%</td></tr><tr><td>₹7L–10L</td><td>20% (above ₹5L)</td><td>10%</td></tr><tr><td>₹10L–12L</td><td>30%</td><td>15%</td></tr><tr><td>₹12L–15L</td><td>30%</td><td>20%</td></tr><tr><td>Above ₹15L</td><td>30%</td><td>30%</td></tr></tbody></table>',
    tblCap: 'Income tax slab comparison FY 2025-26'
  },
  compoundinterest: {
    why: 'Albert Einstein reportedly called compound interest the eighth wonder of the world. In India, instruments like FDs, PPF, and mutual funds all use compounding. Understanding the Rule of 72 — divide 72 by the interest rate to find how many years your money takes to double — helps make smarter investment decisions. At 12% returns, your money doubles every 6 years.',
    feats: ['Calculate compound interest for any principal, rate, and tenure','Support for annual, semi-annual, quarterly, and monthly compounding','Visual growth chart showing exponential growth','Compare simple vs compound interest side by side','Compounding frequency comparison table','Rule of 72 calculator included'],
    tips: ['Higher compounding frequency means more returns — monthly beats annual.','Start investing early — time is the most powerful factor in compounding.','Reinvest your interest/returns to maximize the compounding effect.','PPF compounds annually, FDs can compound quarterly — factor this in.','The Rule of 72: divide 72 by rate to find doubling time.'],
    who: 'Students learning finance, investors comparing instruments, FD holders, PPF contributors, and financial advisors.',
    formula: 'A = P × (1 + r/n)^(n×t), where P = Principal, r = Annual interest rate (decimal), n = Compounding frequency per year, t = Time in years. CI = A – P.',
    example: 'Principal ₹1,00,000 at 8% for 10 years, compounded quarterly: A = 1,00,000 × (1 + 0.08/4)^(4×10) = 1,00,000 × (1.02)^40 = ₹2,20,804. Compound Interest = ₹1,20,804.',
    tbl: '<table><thead><tr><th>Principal</th><th>Rate</th><th>Years</th><th>Compounding</th><th>Maturity</th></tr></thead><tbody><tr><td>₹1,00,000</td><td>7%</td><td>10</td><td>Annual</td><td>₹1,96,715</td></tr><tr><td>₹1,00,000</td><td>7%</td><td>10</td><td>Quarterly</td><td>₹2,00,160</td></tr><tr><td>₹5,00,000</td><td>8%</td><td>15</td><td>Annual</td><td>₹15,86,084</td></tr><tr><td>₹10,00,000</td><td>12%</td><td>20</td><td>Annual</td><td>₹96,46,293</td></tr></tbody></table>',
    tblCap: 'Compound interest growth across scenarios'
  },
  incometax: {
    why: 'Over 7 crore returns were filed in AY 2024-25, yet many taxpayers overpay because they don\'t optimize their regime choice. With the new regime offering zero tax up to ₹12 lakh and lower slab rates, while the old regime provides powerful deductions, calculating your exact liability is crucial for financial planning.',
    feats: ['Compare Old vs New tax regime instantly','Updated for FY 2025-26 with latest slab rates','All major deduction sections supported','Cess and surcharge auto-calculated','Monthly and annual breakdown','Downloadable tax summary'],
    tips: ['Claim all eligible deductions — many miss 80D (health insurance) and 80CCD(1B) (NPS).','Consider the standard deduction of ₹75,000 in new regime.','Advance tax is mandatory if liability exceeds ₹10,000.','Keep Form 16 and receipts organized for quick filing.','Use old regime if total deductions exceed ₹3.75 lakh.'],
    who: 'Salaried employees, self-employed individuals, freelancers planning advance tax, CAs, and HR departments.',
    formula: 'Tax = Sum of (Taxable income in each slab × applicable rate) + 4% Health & Education Cess. Taxable Income = Gross Income – Exemptions – Deductions (old regime) or Gross Income – Standard Deduction (new regime).',
    example: 'Salary ₹12,00,000, old regime with ₹1.5L (80C) + ₹25K (80D) + ₹50K (NPS) = ₹2.25L deductions. Taxable = ₹12L – ₹50K (std) – ₹2.25L = ₹9.25L. Tax = ₹12,500 + ₹85,000 = ₹97,500 + 4% cess = ₹1,01,400.',
    tbl: '<table><thead><tr><th>Income</th><th>Old Regime Tax</th><th>New Regime Tax</th><th>Better Option</th></tr></thead><tbody><tr><td>₹7,50,000</td><td>₹0 (with ₹1.5L 80C)</td><td>₹0 (rebate)</td><td>Either</td></tr><tr><td>₹10,00,000</td><td>₹54,600 (₹2L ded.)</td><td>₹54,600</td><td>Equal</td></tr><tr><td>₹15,00,000</td><td>₹1,17,000 (₹3L ded.)</td><td>₹1,45,600</td><td>Old</td></tr><tr><td>₹20,00,000</td><td>₹2,73,000 (₹3L ded.)</td><td>₹2,99,000</td><td>Old</td></tr></tbody></table>',
    tblCap: 'Tax comparison: Old vs New regime (FY 2025-26)'
  },
  ppf: {
    why: 'Public Provident Fund is India\'s most popular tax-saving instrument with a 15-year lock-in, currently offering 7.1% interest (compounded annually). PPF enjoys EEE status — Exempt at investment (80C), Exempt on interest earned, and Exempt at maturity. The maximum annual contribution is ₹1.5 lakh. A ₹1.5L annual contribution for 15 years at 7.1% yields approximately ₹40.7 lakh at maturity.',
    feats: ['Calculate PPF maturity amount for any contribution','Year-by-year balance breakdown','Partial withdrawal eligibility calculator','Loan against PPF calculation','Extension period (5-year blocks) support','Tax savings under Section 80C'],
    tips: ['Invest before April 5 each year to earn interest for the full year.','The maximum ₹1.5L contribution gives ₹46,800 tax savings at 30% bracket.','Partial withdrawals allowed from 7th year — up to 50% of balance.','Loan facility available from 3rd to 6th year at 1% above PPF rate.','You can extend PPF in 5-year blocks after 15 years with or without contributions.'],
    who: 'Conservative investors seeking guaranteed returns, tax planners maximizing 80C, retirement savers, and parents building long-term corpus.',
    formula: 'PPF uses annual compounding. Balance(n) = Balance(n-1) × (1 + r) + Annual Contribution. Interest calculated on lowest balance between 5th and last day of each month.',
    example: 'Annual contribution ₹1,50,000 for 15 years at 7.1%: Total invested = ₹22,50,000. Maturity value ≈ ₹40,68,209. Interest earned = ₹18,18,209 (completely tax-free).',
    tbl: '<table><thead><tr><th>Annual Deposit</th><th>Rate</th><th>Years</th><th>Invested</th><th>Maturity</th></tr></thead><tbody><tr><td>₹50,000</td><td>7.1%</td><td>15</td><td>₹7,50,000</td><td>₹13,56,070</td></tr><tr><td>₹1,00,000</td><td>7.1%</td><td>15</td><td>₹15,00,000</td><td>₹27,12,139</td></tr><tr><td>₹1,50,000</td><td>7.1%</td><td>15</td><td>₹22,50,000</td><td>₹40,68,209</td></tr><tr><td>₹1,50,000</td><td>7.1%</td><td>25</td><td>₹37,50,000</td><td>₹1,03,08,015</td></tr></tbody></table>',
    tblCap: 'PPF maturity values at 7.1% interest rate'
  },
  fd: {
    why: 'Fixed Deposits remain India\'s most trusted investment, with over ₹200 lakh crore in bank FDs. Current top FD rates range from 7.0% to 8.5% depending on the bank and tenure. Senior citizens get an additional 0.25–0.50% premium. Understanding the impact of compounding frequency and TDS deduction (10% on interest above ₹40,000/year) is crucial for maximizing returns.',
    feats: ['Calculate FD maturity for any amount, rate, and tenure','Support for quarterly, monthly, and annual compounding','Tax calculation with TDS deduction','Senior citizen rate premium toggle','Compare multiple bank rates side by side','Cumulative vs non-cumulative option'],
    tips: ['Split large FDs into ₹5 lakh chunks to stay within DICGC insurance coverage.','Senior citizens: claim up to ₹50,000 interest deduction under 80TTB.','Tax-saver FDs (5-year lock-in) qualify for 80C deduction up to ₹1.5 lakh.','Submit Form 15G/15H if total income is below taxable limit to avoid TDS.','Quarterly compounding gives slightly higher returns than annual.'],
    who: 'Risk-averse investors, senior citizens seeking regular income, short-term savers, and anyone parking emergency funds.',
    formula: 'Maturity = P × (1 + r/n)^(n×t) for cumulative FD. For non-cumulative: Interest per period = P × r/n. Where P = Principal, r = Annual rate, n = Compounding frequency, t = Years.',
    example: 'FD of ₹10,00,000 at 7.5% for 5 years, quarterly compounding: Maturity = 10,00,000 × (1 + 0.075/4)^(4×5) = 10,00,000 × (1.01875)^20 = ₹14,48,502. Interest = ₹4,48,502.',
    tbl: '<table><thead><tr><th>Bank</th><th>1 Year</th><th>3 Years</th><th>5 Years</th><th>Senior Citizen 5Y</th></tr></thead><tbody><tr><td>SBI</td><td>6.80%</td><td>7.00%</td><td>6.50%</td><td>7.50%</td></tr><tr><td>HDFC</td><td>6.60%</td><td>7.10%</td><td>7.00%</td><td>7.75%</td></tr><tr><td>ICICI</td><td>6.70%</td><td>7.10%</td><td>7.00%</td><td>7.50%</td></tr><tr><td>Post Office</td><td>6.90%</td><td>7.10%</td><td>7.50%</td><td>7.50%</td></tr></tbody></table>',
    tblCap: 'Top FD interest rates comparison (May 2026, indicative)'
  },
  mortgage: {
    why: 'Home loans in India have grown to over ₹27 lakh crore outstanding as of 2025. With property prices varying wildly — from ₹3,000/sqft in tier-3 cities to ₹50,000+/sqft in Mumbai — understanding your mortgage affordability and total cost is essential. Banks typically lend 75-80% of property value, and the interest component often exceeds the principal over long tenures.',
    feats: ['EMI calculation with complete amortization schedule','Stamp duty and registration cost estimation','Home loan eligibility based on income','Prepayment impact analysis','Balance transfer savings calculator','Tax benefit under Section 24B and 80C'],
    tips: ['Negotiate processing fees — many banks waive them during festive offers.','Consider 15-year tenure over 20 — saves 20-30% on total interest.','Claim up to ₹2 lakh deduction on interest under Section 24B.','Principal repayment qualifies under 80C up to ₹1.5 lakh.','Review MCLR-linked vs repo-linked rates — repo-linked transmits rate cuts faster.'],
    who: 'First-time home buyers, property investors, NRIs buying property in India, and existing borrowers considering refinancing.',
    formula: 'Same as EMI formula: EMI = [P × R × (1+R)^N] / [(1+R)^N – 1]. Eligibility: Max loan = 60× monthly salary (approx). LTV ratio: 75-90% of property value.',
    example: 'Property ₹80 lakh, 80% LTV = ₹64 lakh loan at 8.5% for 20 years. EMI = ₹55,540. Total payment = ₹1,33,29,600. Total interest = ₹69,29,600. Tax saved (30% bracket): ~₹6.9 lakh over tenure.',
    tbl: '<table><thead><tr><th>Loan Amount</th><th>Rate</th><th>20-yr EMI</th><th>Total Interest</th><th>15-yr EMI</th><th>Interest Saved</th></tr></thead><tbody><tr><td>₹30L</td><td>8.5%</td><td>₹26,035</td><td>₹32,48,304</td><td>₹29,542</td><td>₹9,50,744</td></tr><tr><td>₹50L</td><td>8.5%</td><td>₹43,391</td><td>₹54,13,840</td><td>₹49,236</td><td>₹15,84,600</td></tr><tr><td>₹75L</td><td>8.5%</td><td>₹65,087</td><td>₹81,20,760</td><td>₹73,855</td><td>₹23,76,900</td></tr></tbody></table>',
    tblCap: 'Home loan cost: 20-year vs 15-year comparison'
  },
  simpleinterest: {
    why: 'Simple interest is the foundation of all financial calculations. Unlike compound interest, SI calculates interest only on the original principal. It is used in short-term loans, government bonds, car loans (flat rate), and some savings instruments. Understanding the difference between flat rate (SI-based) and reducing balance (CI-based) is crucial — a 10% flat rate is roughly equivalent to 18-19% reducing balance rate.',
    feats: ['Calculate simple interest for any principal, rate, and time','Convert between flat rate and reducing balance rate','Compare SI vs compound interest side by side','Support for days, months, and years','Reverse calculation — find rate or time from interest amount','Clean, instant results'],
    tips: ['Car loan "flat rates" are misleading — always calculate the effective reducing rate.','SI is always less than CI for the same rate and tenure beyond 1 year.','For short-term deposits (< 1 year), SI and CI difference is negligible.','Government savings certificates often use simple interest.','Always compare effective annual rate, not nominal rate.'],
    who: 'Students learning finance basics, borrowers comparing flat vs reducing rates, short-term deposit holders, and car loan applicants.',
    formula: 'SI = (P × R × T) / 100, where P = Principal, R = Annual rate (%), T = Time in years. Total Amount = P + SI.',
    example: 'Principal ₹5,00,000 at 10% for 3 years: SI = (5,00,000 × 10 × 3) / 100 = ₹1,50,000. Total amount = ₹6,50,000.',
    tbl: '<table><thead><tr><th>Principal</th><th>Rate</th><th>Time</th><th>Simple Interest</th><th>Total</th></tr></thead><tbody><tr><td>₹1,00,000</td><td>8%</td><td>1 year</td><td>₹8,000</td><td>₹1,08,000</td></tr><tr><td>₹5,00,000</td><td>10%</td><td>3 years</td><td>₹1,50,000</td><td>₹6,50,000</td></tr><tr><td>₹10,00,000</td><td>7%</td><td>5 years</td><td>₹3,50,000</td><td>₹13,50,000</td></tr></tbody></table>',
    tblCap: 'Simple interest calculation examples'
  }
};
