#!/usr/bin/env node
/**
 * Calc Labz — Unified Build Script
 * ====================================
 * Single source of truth: generates all derived config files from
 * the calculator-registry.json + generate-prerender.js.
 *
 * Generates:
 *   1. Pre-rendered HTML files (calculator + category + blog pages)
 *   2. sitemap.xml (deduplicated, with category + blog pages)
 *   3. serve.json rewrites (ALL calculators, categories, blog, 404 catch-all)
 *   4. vercel.json rewrites (ALL calculators, categories, blog, 404 catch-all)
 *
 * Usage:  node scripts/generate-all.js
 */

'use strict';

var fs   = require('fs');
var path = require('path');

var ROOT         = path.resolve(__dirname, '..');
var REGISTRY     = require('./calculator-registry.json');
var SERVE_PATH   = path.join(ROOT, 'serve.json');
var VERCEL_PATH  = path.join(ROOT, 'vercel.json');
var SITEMAP_PATH = path.join(ROOT, 'sitemap.xml');
var TODAY = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

// Import prerender module — this runs pre-rendering as side effect
var prerender = require('./generate-prerender.js');
var CATEGORIES = prerender.CATEGORIES || [];

// Import trust page generator — generates about, privacy, terms, contact, disclaimer, editorial-policy
var trustPages = require('./generate-trust-pages.js');

// ── 1. GENERATE SITEMAP.XML ────────────────────────────────────────────────

function generateSitemap() {
  var BASE = 'https://calclabz.com';
  var emittedUrls = new Set();

  function addUrl(xml, loc, lastmod, changefreq, priority) {
    if (emittedUrls.has(loc)) return xml;
    emittedUrls.add(loc);
    return xml + '  <url><loc>' + loc + '</loc><lastmod>' + lastmod + '</lastmod><changefreq>' + changefreq + '</changefreq><priority>' + priority + '</priority></url>\n';
  }

  var xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<!--\n';
  xml += '  Calc Labz — Auto-generated Sitemap (deduplicated)\n';
  xml += '  Generated by: node scripts/generate-all.js\n';
  xml += '  Date: ' + TODAY + '\n';
  xml += '  Covers: Homepage, Static Pages, Category Pages, Blog Posts, All Calculators\n';
  xml += '-->\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n';
  xml += '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n';
  xml += '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9\n';
  xml += '        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n\n';

  // Homepage
  xml += '  <!-- HOMEPAGE -->\n';
  xml = addUrl(xml, BASE + '/', TODAY, 'weekly', '1.0');
  xml += '\n';

  // Static pages
  xml += '  <!-- STATIC PAGES -->\n';
  ['about', 'contact', 'privacy', 'terms', 'disclaimer', 'editorial-policy'].forEach(function(page) {
    var pri = (page === 'about' || page === 'contact') ? '0.5' : '0.4';
    xml = addUrl(xml, BASE + '/' + page, TODAY, 'monthly', pri);
  });
  xml += '\n';

  // Category pages
  xml += '  <!-- CATEGORY PAGES (' + CATEGORIES.length + ') -->\n';
  CATEGORIES.forEach(function(cat) {
    xml = addUrl(xml, BASE + '/' + cat.slug, TODAY, 'weekly', '0.8');
  });
  xml += '\n';

  // Blog posts — read from blog-posts.js
  var blogPosts = [];
  try {
    var vm = require('vm');
    var blogSrc = fs.readFileSync(path.join(ROOT, 'assets', 'js', 'blog-posts.js'), 'utf8');
    var sandbox = {};
    vm.createContext(sandbox);
    vm.runInContext(blogSrc, sandbox);
    blogPosts = sandbox.BLOG_POSTS || [];
  } catch (e) { /* ignore */ }

  if (blogPosts.length) {
    xml += '  <!-- BLOG POSTS (' + blogPosts.length + ') -->\n';
    blogPosts.forEach(function(post) {
      var dateStr = TODAY;
      if (post.date) {
        var months = { Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06',
                       Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12' };
        var parts = post.date.split(' ');
        dateStr = (parts[1] || '2026') + '-' + (months[parts[0]] || '01') + '-01';
      }
      xml = addUrl(xml, BASE + '/blog/' + post.slug, dateStr, 'monthly', '0.7');
    });
    xml += '\n';
  }

  // Group calculators by category
  var catOrder = ['math', 'finance', 'health', 'everyday', 'unit', 'datetime', 'engineering', 'construction', 'education', 'science'];
  var catNames = {
    math: 'MATH', finance: 'FINANCE', health: 'HEALTH',
    everyday: 'EVERYDAY / LIFESTYLE', unit: 'UNIT CONVERSION',
    datetime: 'TIME & DATE', engineering: 'SCIENCE / ENGINEERING',
    construction: 'CONSTRUCTION', education: 'EDUCATION', science: 'SCIENCE'
  };

  catOrder.forEach(function(cat) {
    var entries = REGISTRY.filter(function(c) { return c.cat === cat; });
    if (!entries.length) return;
    xml += '  <!-- CALCULATORS — ' + (catNames[cat] || cat.toUpperCase()) + ' (' + entries.length + ') -->\n';
    entries.forEach(function(c) {
      xml = addUrl(xml, BASE + '/' + c.slug, TODAY, 'monthly', c.priority || '0.6');
    });
    xml += '\n';
  });

  // Unknown category calcs
  var unknownEntries = REGISTRY.filter(function(c) {
    return catOrder.indexOf(c.cat) === -1;
  });
  if (unknownEntries.length) {
    xml += '  <!-- CALCULATORS — OTHER (' + unknownEntries.length + ') -->\n';
    unknownEntries.forEach(function(c) {
      xml = addUrl(xml, BASE + '/' + c.slug, TODAY, 'monthly', c.priority || '0.5');
    });
    xml += '\n';
  }

  xml += '</urlset>\n';

  fs.writeFileSync(SITEMAP_PATH, xml, 'utf8');
  console.log('  ✓  sitemap.xml — ' + emittedUrls.size + ' unique URLs');
  return emittedUrls.size;
}

// ── 2. UPDATE SERVE.JSON REWRITES ──────────────────────────────────────────

function updateServeRewrites() {
  var serve = JSON.parse(fs.readFileSync(SERVE_PATH, 'utf8'));

  // Enable clean URLs so /emi-calculator auto-resolves to /emi-calculator.html
  serve.cleanUrls = true;

  // Static page rewrites — point to actual HTML files with pre-rendered content
  var staticRewrites = [
    { source: '/about',             destination: '/about.html' },
    { source: '/contact',           destination: '/contact.html' },
    { source: '/privacy',           destination: '/privacy.html' },
    { source: '/terms',             destination: '/terms.html' },
    { source: '/disclaimer',        destination: '/disclaimer.html' },
    { source: '/editorial-policy',  destination: '/editorial-policy.html' }
  ];

  // ALL calculator rewrites (every registry entry gets a rewrite)
  var calcRewrites = REGISTRY.map(function(c) {
    return { source: '/' + c.slug, destination: '/' + c.slug + '.html' };
  });

  // Category page rewrites
  var categoryRewrites = CATEGORIES.map(function(cat) {
    return { source: '/' + cat.slug, destination: '/' + cat.slug + '.html' };
  });

  // Blog post rewrites to static HTML (MUST come before blog catch-all)
  var blogRewrites = [];
  try {
    var vm = require('vm');
    var blogSrc = fs.readFileSync(path.join(ROOT, 'assets', 'js', 'blog-posts.js'), 'utf8');
    var sandbox = {};
    vm.createContext(sandbox);
    vm.runInContext(blogSrc, sandbox);
    (sandbox.BLOG_POSTS || []).forEach(function(post) {
      blogRewrites.push({
        source: '/blog/' + post.slug,
        destination: '/blog/' + post.slug + '.html'
      });
    });
  } catch (e) { /* ignore */ }

  // Note: cleanUrls:true handles .html resolution automatically.
  // Only add specific SPA routes — no broad catch-alls that override cleanUrls.
  var spaRoutes = [
    { source: '/blog', destination: '/index.html' }
  ];

  serve.rewrites = staticRewrites
    .concat(calcRewrites)
    .concat(categoryRewrites)
    .concat(blogRewrites)
    .concat(spaRoutes);

  fs.writeFileSync(SERVE_PATH, JSON.stringify(serve, null, 2) + '\n', 'utf8');
  console.log('  ✓  serve.json — ' + calcRewrites.length + ' calculators + ' + categoryRewrites.length + ' categories + ' + blogRewrites.length + ' blog + 404');
}

// ── 3. UPDATE VERCEL.JSON REWRITES ─────────────────────────────────────────

function updateVercelRewrites() {
  var vercel = JSON.parse(fs.readFileSync(VERCEL_PATH, 'utf8'));

  // Keep existing redirects intact
  var existingRedirects = vercel.redirects || [];
  var existingHeaders = vercel.headers || [];

  // Build new rewrites
  var rewrites = [];

  // Static pages — real HTML files with pre-rendered content
  rewrites.push({ source: '/about', destination: '/about.html' });
  rewrites.push({ source: '/contact', destination: '/contact.html' });
  rewrites.push({ source: '/privacy', destination: '/privacy.html' });
  rewrites.push({ source: '/terms', destination: '/terms.html' });
  rewrites.push({ source: '/disclaimer', destination: '/disclaimer.html' });
  rewrites.push({ source: '/editorial-policy', destination: '/editorial-policy.html' });

  // ALL calculator rewrites
  REGISTRY.forEach(function(c) {
    rewrites.push({ source: '/' + c.slug, destination: '/' + c.slug + '.html' });
  });

  // Category page rewrites
  CATEGORIES.forEach(function(cat) {
    rewrites.push({ source: '/' + cat.slug, destination: '/' + cat.slug + '.html' });
  });

  // Blog post rewrites
  try {
    var vm = require('vm');
    var blogSrc = fs.readFileSync(path.join(ROOT, 'assets', 'js', 'blog-posts.js'), 'utf8');
    var sandbox = {};
    vm.createContext(sandbox);
    vm.runInContext(blogSrc, sandbox);
    (sandbox.BLOG_POSTS || []).forEach(function(post) {
      rewrites.push({
        source: '/blog/' + post.slug,
        destination: '/blog/' + post.slug + '.html'
      });
    });
  } catch (e) { /* ignore */ }

  // Blog catch-all for non-pre-rendered blog routes
  rewrites.push({ source: '/blog/:path*', destination: '/index.html' });

  // 404 catch-all (must be last)
  rewrites.push({
    source: '/((?!assets|manifest\\.json|robots\\.txt|sitemap\\.xml|sw\\.js|og-image\\.png|icon-192\\.png|icon-512\\.png|calclabz-logo\\.png).*)',
    destination: '/404.html'
  });

  vercel.redirects = existingRedirects;
  vercel.rewrites = rewrites;
  vercel.headers = existingHeaders;

  fs.writeFileSync(VERCEL_PATH, JSON.stringify(vercel, null, 2) + '\n', 'utf8');
  console.log('  ✓  vercel.json — ' + (rewrites.length - 2) + ' rewrites + blog catch-all + 404 catch-all');
}

// ── 4. VALIDATE ────────────────────────────────────────────────────────────

function validate() {
  // Check that all pre-rendered HTML files exist
  var missing = [];
  REGISTRY.forEach(function(c) {
    var file = path.join(ROOT, c.slug + '.html');
    if (!fs.existsSync(file)) missing.push(c.slug);
  });

  if (missing.length) {
    console.warn('\n⚠️  Missing HTML files for ' + missing.length + ' calculators:');
    missing.slice(0, 10).forEach(function(s) { console.warn('   ' + s); });
    if (missing.length > 10) console.warn('   ... and ' + (missing.length - 10) + ' more');
  } else {
    console.log('  ✓  All ' + REGISTRY.length + ' calculator HTML files exist');
  }

  // Check category pages
  var missingCats = [];
  CATEGORIES.forEach(function(cat) {
    var file = path.join(ROOT, cat.slug + '.html');
    if (!fs.existsSync(file)) missingCats.push(cat.slug);
  });

  if (missingCats.length) {
    console.warn('\n⚠️  Missing category HTML files:');
    missingCats.forEach(function(s) { console.warn('   ' + s); });
  } else {
    console.log('  ✓  All ' + CATEGORIES.length + ' category HTML files exist');
  }

  // Check blog directory
  var blogDir = path.join(ROOT, 'blog');
  if (fs.existsSync(blogDir)) {
    var blogFiles = fs.readdirSync(blogDir).filter(function(f) { return f.endsWith('.html'); });
    console.log('  ✓  ' + blogFiles.length + ' blog HTML files exist');
  }

  // Check 404
  if (fs.existsSync(path.join(ROOT, '404.html'))) {
    console.log('  ✓  404.html exists');
  } else {
    console.warn('  ⚠  404.html is missing!');
  }
}

// ── MAIN ────────────────────────────────────────────────────────────────────

console.log('\n🔧 Calc Labz — Unified Build\n');

var count = generateSitemap();
updateServeRewrites();
updateVercelRewrites();
// Pre-render already ran via require('./generate-prerender.js')
validate();

console.log('\n✅ Build complete. ' + count + ' URLs in sitemap.\n');
