#!/usr/bin/env node
/**
 * Calc Labz — Unified Build Script
 * ====================================
 * Single source of truth: generates all derived config files from
 * the calculator-registry.json + generate-prerender.js.
 *
 * Generates:
 *   1. sitemap.xml
 *   2. serve.json rewrites
 *   3. Pre-rendered HTML files (via generate-prerender.js)
 *
 * Usage:  node scripts/generate-all.js
 *
 * NOTE: vercel.json redirects are managed separately (they use
 * regex patterns, not individual entries) but this script validates
 * that all calculator slugs have matching vercel.json coverage.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = path.resolve(__dirname, '..');
const REGISTRY    = require('./calculator-registry.json');
const SERVE_PATH  = path.join(ROOT, 'serve.json');
const SITEMAP_PATH = path.join(ROOT, 'sitemap.xml');
const TODAY = new Date().toISOString().split('T')[0]; // YYYY-MM-DD

// ── 1. GENERATE SITEMAP.XML ────────────────────────────────────────────────

function generateSitemap() {
  const BASE = 'https://calclabz.com';

  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<!--\n';
  xml += '  Calc Labz — Auto-generated Sitemap\n';
  xml += '  Generated by: node scripts/generate-all.js\n';
  xml += '  Date: ' + TODAY + '\n';
  xml += '  Covers: Homepage, Static Pages, Blog Posts, All Calculators\n';
  xml += '-->\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n';
  xml += '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n';
  xml += '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9\n';
  xml += '        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n\n';

  // Homepage
  xml += '  <!-- HOMEPAGE -->\n';
  xml += '  <url>\n';
  xml += '    <loc>' + BASE + '/</loc>\n';
  xml += '    <lastmod>' + TODAY + '</lastmod>\n';
  xml += '    <changefreq>weekly</changefreq>\n';
  xml += '    <priority>1.0</priority>\n';
  xml += '  </url>\n\n';

  // Static pages
  xml += '  <!-- STATIC PAGES -->\n';
  ['about', 'privacy', 'terms'].forEach(function(page) {
    xml += '  <url><loc>' + BASE + '/' + page + '</loc><lastmod>' + TODAY + '</lastmod><changefreq>monthly</changefreq><priority>0.' + (page === 'about' ? '5' : '4') + '</priority></url>\n';
  });
  xml += '\n';

  // Blog posts (from registry blog entries)
  var blogEntries = REGISTRY.filter(function(c) { return c.blogSlug; });
  if (blogEntries.length) {
    xml += '  <!-- BLOG POSTS (' + blogEntries.length + ') -->\n';
    blogEntries.forEach(function(c) {
      xml += '  <url><loc>' + BASE + '/blog/' + c.blogSlug + '</loc><lastmod>' + (c.blogDate || TODAY) + '</lastmod><changefreq>monthly</changefreq><priority>' + (c.blogPriority || '0.7') + '</priority></url>\n';
    });
    xml += '\n';
  }

  // Group calculators by category
  var catOrder = ['math', 'finance', 'health', 'everyday', 'unit', 'datetime', 'engineering', 'construction', 'education'];
  var catNames = {math:'MATH', finance:'FINANCE', health:'HEALTH', everyday:'EVERYDAY / LIFESTYLE', unit:'UNIT CONVERSION', datetime:'TIME & DATE', engineering:'SCIENCE / ENGINEERING', construction:'CONSTRUCTION', education:'EDUCATION'};

  catOrder.forEach(function(cat) {
    var entries = REGISTRY.filter(function(c) { return c.cat === cat; });
    if (!entries.length) return;
    xml += '  <!-- CALCULATORS — ' + (catNames[cat] || cat.toUpperCase()) + ' -->\n';
    entries.forEach(function(c) {
      xml += '  <url><loc>' + BASE + '/' + c.slug + '</loc><lastmod>' + TODAY + '</lastmod><changefreq>monthly</changefreq><priority>' + (c.priority || '0.6') + '</priority></url>\n';
    });
    xml += '\n';
  });

  xml += '</urlset>\n';

  fs.writeFileSync(SITEMAP_PATH, xml, 'utf8');
  var calcCount = REGISTRY.length;
  console.log('  ✓  sitemap.xml — ' + calcCount + ' calculators + blog + static pages');
  return calcCount;
}

// ── 2. UPDATE SERVE.JSON REWRITES ──────────────────────────────────────────

function updateServeRewrites() {
  var serve = JSON.parse(fs.readFileSync(SERVE_PATH, 'utf8'));

  // Preserve non-calculator rewrites (blog, about, privacy, terms, fallback)
  var staticRewrites = [
    { source: '/blog/**',  destination: '/index.html' },
    { source: '/about',    destination: '/index.html' },
    { source: '/privacy',  destination: '/index.html' },
    { source: '/terms',    destination: '/index.html' }
  ];

  // Pre-rendered calculator rewrites
  var preRenderedSlugs = REGISTRY.filter(function(c) { return c.prerender; });
  var calcRewrites = preRenderedSlugs.map(function(c) {
    return { source: '/' + c.slug, destination: '/' + c.slug + '.html' };
  });

  // Non-prerendered calculators fall through to the SPA catch-all
  var fallback = [{ source: '/**', destination: '/index.html' }];

  serve.rewrites = staticRewrites.concat(calcRewrites).concat(fallback);
  fs.writeFileSync(SERVE_PATH, JSON.stringify(serve, null, 2) + '\n', 'utf8');
  console.log('  ✓  serve.json — ' + calcRewrites.length + ' calculator rewrites + ' + staticRewrites.length + ' static');
}

// ── 3. RUN PRE-RENDER ──────────────────────────────────────────────────────

function runPrerender() {
  // The existing generate-prerender.js handles HTML generation
  require('./generate-prerender.js');
}

// ── 4. VALIDATE ────────────────────────────────────────────────────────────

function validate() {
  var vercel = JSON.parse(fs.readFileSync(path.join(ROOT, 'vercel.json'), 'utf8'));
  var vercelSources = (vercel.rewrites || []).map(function(r) { return r.source; });

  var missing = [];
  REGISTRY.filter(function(c) { return c.prerender; }).forEach(function(c) {
    var slug = '/' + c.slug;
    if (!vercelSources.includes(slug)) {
      missing.push(slug);
    }
  });

  if (missing.length) {
    console.warn('\n⚠️  Missing from vercel.json rewrites:');
    missing.forEach(function(s) { console.warn('   ' + s); });
  } else {
    console.log('  ✓  All pre-rendered slugs found in vercel.json rewrites');
  }
}

// ── MAIN ────────────────────────────────────────────────────────────────────

console.log('\n🔧 Calc Labz — Unified Build\n');

var count = generateSitemap();
updateServeRewrites();
runPrerender();
validate();

console.log('\n✅ Build complete. ' + count + ' calculators processed.\n');
